title: Robert Guzman's Portfolio
description: A professional portfolio showcasing my work in game development, programming, and digital art.
theme: minima

include:
  - unity
  - ink
  - web-design
  - python
  - concept-art
  - arduino

#Social links
email: ro305529@ucf.edu
