title: Robert Guzman's Portfolio
description: A professional portfolio showcasing my work in game development, programming, and digital art.
theme: minima

# Social links
email: your-email@example.com
linkedin: https://www.linkedin.com/in/your-profile/
github: https://github.com/your-username
