title: Robert Guzman Portfolio
description: A professional portfolio showcasing my work in game development, programming, and digital art.
theme: minima
<<<<<<< HEAD
=======

# Social links
email: ro305529@ucf.edu
linkedin: https://www.linkedin.com/in/robert-guzman-designer/
github: https://github.com/Bobby-Gman
>>>>>>> parent of dc5c9a2 (Update _config.yml)
