title: Robert Guzman's Portfolio
description: A professional portfolio showcasing my work in game development, programming, and digital art.

#Site settings
remote_theme: "mmistakes/minimal-mistakes"
baseurl:
url: https://bobby-gman.github.io/Guzman-portfolio/

# Social links
email: ro305529@ucf.edu
linkedin: https://www.linkedin.com/in/robert-guzman-designer/
github: https://github.com/Bobby-Gman

plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  
theme_settings:
  layout: single
  show_excerpts: true
  social_links: true
